package constants;

public class City {
	public final static int CITY_RADIUS = 25;
	public final static int DELTA = CITY_RADIUS / 2;

	public final static int RESEARCH_STATION_TOP_OFFSET = 2;
	public final static int RESEARCH_STATION_SIDE_OFFSET = 5;
	public final static int RESEARCH_STATION_MIDDLE_OFFSET = 9;
	public final static int RESEARCH_STATION_BOTTOM_OFFSET = 19;

	public final static String ALGIERS = "Algiers";
	public final static String ATLANTA = "Atlanta";
	public final static String BAGHDAD = "Baghdad";
	public final static String BANGKOK = "Bangkok";
	public final static String BEIJING = "Beijing";
	public final static String BOGOTA = "Bogota";
	public final static String BUENOS_AIRES = "Buenos Aires";
	public final static String CAIRO = "Cairo";
	public final static String CHENNAI = "Chennai";
	public final static String CHICAGO = "Chicago";
	public final static String DELHI = "Delhi";
	public final static String ESSEN = "Essen";
	public final static String HO_CHI_MINH_CITY = "Ho Chi Minh City";
	public final static String HONG_KONG = "Hong Kong";
	public final static String ISTANBUL = "Istanbul";
	public final static String JAKARTA = "Jakarta";
	public final static String JOHANNESBURG = "Johannesburg";
	public final static String KARACHI = "Karachi";
	public final static String KHARTOUM = "Khartoum";
	public final static String KINSHASA = "Kinshasa";
	public final static String KOLKATA = "Kolkata";
	public final static String LAGOS = "Lagos";
	public final static String LIMA = "Lima";
	public final static String LONDON = "London";
	public final static String LOS_ANGELES = "Los Angeles";
	public final static String MADRID = "Madrid";
	public final static String MANILA = "Manila";
	public final static String MEXICO_CITY = "Mexico City";
	public final static String MIAMI = "Miami";
	public final static String MILAN = "Milan";
	public final static String MONTREAL = "Montreal";
	public final static String MOSCOW = "Moscow";
	public final static String MUMBAI = "Mumbai";
	public final static String NEW_YORK = "New York";
	public final static String OSAKA = "Osaka";
	public final static String PARIS = "Paris";
	public final static String RIYADH = "Riyadh";
	public final static String SAN_FRANCISCO = "San Francisco";
	public final static String SANTIAGO = "Santiago";
	public final static String SAO_PAULO = "Sao Paulo";
	public final static String SEOUL = "Seoul";
	public final static String SHANGHAI = "Shanghai";
	public final static String ST_PETERSBURG = "St. Petersburg";
	public final static String SYDNEY = "Sydney";
	public final static String TAIPEI = "Taipei";
	public final static String TEHRAN = "Tehran";
	public final static String TOKYO = "Tokyo";
	public final static String WASHINGTON = "Washington";
}
